ADD_USER = 'User added successfully'
UPDATE_USER = 'User updated successfully'
WORKING_UNDER_IS_NOT_A_SUPERVISOR = 'Working under is not a Supervisor'
WORKING_UNDER_IS_NOT_A_ADMIN = 'Working under is not a Admin'
EMAIL_FOUND = 'Email is already registered'
EMAIL_NOT_FOUND = 'Email id is not registered'
INVALID_ROLE = 'Given role is invalid'
INVALID_CREDENTIALS = 'Invalid Credentials'
USER_UNAUTHORIZED = 'Not authorized to perform the following action'
USER_NOT_FOUND = 'User not found'
USER_ALREADY_EXISTS = 'User is already registered'
USER_INACTIVE = 'User is inactive'


ADD_COMPANY = 'Company added successfully'
COMPANY_NOT_FOUND = 'Company not found'
COMPANY_ALREADY_EXISTS = 'Company with same name already exists'
UPDATE_COMPANY = 'Company updated Successfully'
DELETE_COMPANY = 'Company deleted successfully'
